// GENERIC APP STATES
export const INITIAL_STATE = "INITIAL_STATE";
export const SUCCESS_STATE = "SUCCESS_STATE";
export const FAILURE_STATE = "FAILURE_STATE";

// CUSTOM STATES
export const LOGIN_CODE_PROCESING = "LOGIN_CODE_PROCESING";
export const LOGIN_CODE_REQUESTING = "LOGIN_CODE_REQUESTING";
export const LOGIN_CODE_REQUEST_SUCCESS = "LOGIN_CODE_REQUEST_SUCCESS";
export const LOGIN_CODE_REQUEST_FAILURE = "LOGIN_CODE_REQUEST_FAILURE";

export const OAUTH_LOGIN_TOKEN_REQUEST = "LOGIN_TOKEN_REQUEST";
export const OAUTH_LOGIN_TOKEN_REQUEST_SUCCESS = "LOGIN_TOKEN_REQUEST_SUCCESS";
export const OAUTH_LOGIN_TOKEN_REQUEST_FAILURE = "LOGIN_TOKEN_REQUEST_FAILURE";

export const LOGOUT = "LOGOUT";
